/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Database;

import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class Sigin_form extends javax.swing.JFrame {
    int op=1;
    
    public Sigin_form() {
        initComponents();
        ch_light.setSelected(true);
        
    }
    
     public Sigin_form(int op) {
        initComponents();
        switch(op){
            case 1:{
                setColor(255, 255, 255);
                ch_light.setSelected(true);
            }break;
            case 2:{
                setColor(102, 102, 102);
                ch_dark.setSelected(true);
            }break;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ch_dark = new javax.swing.JCheckBox();
        ch_light = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Password : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(540, 300, 140, 30);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(610, 40, 0, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\My_Java\\src\\images\\icons8-male-user-100.png")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(640, 20, 120, 100);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("create new account? ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(530, 450, 210, 20);

        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_username);
        txt_username.setBounds(540, 230, 260, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\My_Java\\src\\images\\icons8-user-35.png")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(470, 340, 40, 40);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setText("UserName :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(540, 200, 140, 30);

        txt_pass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(txt_pass);
        txt_pass.setBounds(530, 330, 280, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\My_Java\\src\\images\\icons8-user-35.png")); // NOI18N
        jLabel7.setText("jLabel5");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 240, 40, 40);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setText("SIG IN YOUR ACCOUNT");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(550, 120, 320, 60);

        buttonGroup1.add(ch_dark);
        ch_dark.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ch_dark.setText("Dark_Mode");
        ch_dark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_darkActionPerformed(evt);
            }
        });
        jPanel1.add(ch_dark);
        ch_dark.setBounds(720, 500, 120, 25);

        buttonGroup1.add(ch_light);
        ch_light.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ch_light.setText("Light_Mode");
        ch_light.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch_lightActionPerformed(evt);
            }
        });
        jPanel1.add(ch_light);
        ch_light.setBounds(520, 500, 120, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 970, 540);

        setSize(new java.awt.Dimension(983, 576));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    void setColor(int r,int g,int b){
        jPanel1.setBackground(new Color(r, g, b));
       txt_username.setBackground(new Color(r, g, b));
       txt_pass.setBackground(new Color(r, g, b));
       btn_register.setBackground(new Color(r, g, b));
        
    }
    private void ch_darkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_darkActionPerformed
        setColor(102, 102, 102);
        op=2;
    }//GEN-LAST:event_ch_darkActionPerformed

    private void ch_lightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch_lightActionPerformed
         setColor(255, 255, 255);
         op=1;
    }//GEN-LAST:event_ch_lightActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        Sigup_form obj = new Sigup_form(op);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sigin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sigin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sigin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sigin_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sigin_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ch_dark;
    private javax.swing.JCheckBox ch_light;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
